### ISSUE TITLE
Building a plugin for 4D v13

### ISSUE THREAD

**Issue by kimdaveconley** [miyako/4d-plugin-common-crypto#1]
Miyako,  Thanks so much for this plugin.  It looks like it will fit the bill for what I need.  I'm sorry for my ignorance, but I wonder if you could share how I actually build a plugin bundle from what you have here.  I need to build on for 4D v13.5 and v15 and I've never built a plugin before.

Thanks

**Comment by miyako** [comment]
Hello,

where did you get the idea that you need to "build" the plugin?
there is absolutely no need for that.
just click on "download zip".

> 2015/09/09 22:29、kimdaveconley notifications@github.com のメール：
> 
> Miyako, Thanks so much for this plugin. It looks like it will fit the bill for what I need. I'm sorry for my ignorance, but I wonder if you could share how I actually build a plugin bundle from what you have here. I need to build on for 4D v13.5 and v15 and I've never built a plugin before.

宮古 啓介
セールス・エンジニア

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/JP

**Comment by kimdaveconley** [comment]
Oh. It will work with v13 and up?

**Comment by miyako** [comment]
yes, v11 and above, as long as you are not using PPC or OS X 10.5, (for THAT you’d have to build from source)

> 2015/09/10 12:24、kimdaveconley notifications@github.com のメール：
> Oh. It will work with v13 and up?

宮古 啓介
セールス・エンジニア

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/JP

**Comment by kimdaveconley** [comment]
Thanks Miyako.

So what I'm finding is that in order to use the plugin on a brand new v13.5 db I need to copy the bundle from the Common Crypto.4dbase package under the v11 folder.  If I use the bundle from the package right inside the Common Crypto folder it doesn't show up as a plugin in the v13.5 db.

On v15 I can use the bundle from the package right inside the Common Crypto folder and it recognizes it.  

I just want to confirm that this is correct and that I'm not screwing this up.

Also just want to confirm that all I'd need to include in my build is the Plugin bundle and nothing else.

Again, I'm so sorry for my lack of understanding on this and really appreciate your patience with me.

Thanks!

David

**Comment by miyako** [comment]
that’s because in v14, a new plugin architecture was introduced,
which is carbon-free and resources free.

you can use either type in v14 and v15,
but future versions (including Mac 64 bits) of 4D will only recognise v14 plugins.

a v11 plugin is compatible with any version above v11,
a v14 plugin is compatible with any version above v14.

I don’t create plugins for v11, v12, v13, v14, v15, because it is nonsense.

> 2015/09/10 23:11、kimdaveconley notifications@github.com のメール：
>  If I use the bundle from the package right inside the Common Crypto folder it doesn't show up as a plugin in the v13.5 db.

宮古 啓介
セールス・エンジニア

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/JP

**Comment by miyako** [comment]
yes, you only need to include the bundle, found inside the sample database.

> 2015/09/10 23:11、kimdaveconley notifications@github.com のメール：
> Also just want to confirm that all I'd need to include in my build is the Plugin bundle and nothing else.

宮古 啓介
セールス・エンジニア

株式会社フォーディー・ジャパン
〒150-0043
東京都渋谷区道玄坂1-10-2 渋谷THビル6F
Tel: 03-6427-8441
Fax: 03-6427-8449

Keisuke.Miyako@4d.com
www.4D.com/JP

**Comment by kimdaveconley** [comment]
Thank you very much for the plugin.  I'm on my way!

David
