### ISSUE TITLE
32bit bundle

### ISSUE THREAD

**Issue by olekrisek** [miyako/4d-plugin-common-crypto#10]
Hello, 
I see that this works fine for 64 bit applications. I need this for 32-bit version of 4D v17. Is there a bundle version for 32-bit binaries somewhere ?

**Comment by miyako** [comment]
you can switch the "branch" to "carbon"

https://github.com/miyako/4d-plugin-common-crypto/tree/carbon

but the build is obviously old.

if you need a 32-bit build based on the latest source, you can compile yourself on Mojave.

**Comment by olekrisek** [comment]
Thank you, exactly what I Needed.
