### ISSUE TITLE
PBKDF2

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-common-crypto#2]
hi, i need a PBKDF2 encryption, before i code it in 4D, juste wondering if it already exists ? :) thx

**Comment by miyako** [comment]
Hello, PBKDF2 is currently not supported by the plugin, but the underlying OpenSSL library is capable of it. You could implement it yourself,

https://git.openssl.org/gitweb/?p=openssl.git;a=blob;f=crypto/evp/p5_crpt2.c

or if you would like the work done for you instead, please contact Info-JP@4D.com

**Comment by miyako** [comment]
done in 3.9.0
