### ISSUE TITLE
We do not see the methods in 4D

### ISSUE THREAD

**Issue by christianschneider89** [miyako/4d-plugin-common-crypto#4]
Hello

We tried to use your plugin on 4D v13.5 (172101) on a Mac OS X 10.8.5 with a Windows 10 Professional or a Mac OS X Client.
We do not see the Plugin Methods within 4D Explorer.
I tried a older version from github, but with no other result.
We took "Common Crypto.bundle" and copied it in the Plugins Folder of a new DB.

Do you now why this happens?

Thanks
Chris

**Comment by miyako** [comment]
for v13 and under you need to use the old (RSR) architecture; go to the v11 folder.
