### ISSUE TITLE
Common Crypto vs PHP md5

### ISSUE THREAD

**Issue by olivierfaure** [miyako/4d-plugin-common-crypto#5]
Why result is different between Common Crypto and PHP (common crypto md5 seems not good) ?

1. $ok:=PHP Executer("";"md5";$crypté;"zozo")
2. $crypté2:=MD5 ("zozo")

**Comment by miyako** [comment]
you are passing a text, not blob, so the result is a hash of ""

try

CONVERTIR DEPUIS TEXTE ("zozo";"utf-8";$zozo)
$crypté2:=MD5 ($zozo)
