### ISSUE TITLE
SHA3-512

### ISSUE THREAD

**Issue by floreagyorgy** [miyako/4d-plugin-common-crypto#6]
Dear Miyako,
Thank you very much for your plugins, I use more of them. Currently, I use SHA512 which I think generates SHA-2 type hash (Sorry, I'm not an expert of crypto).
However, I would need SHA-3 type hash in next version of my 4D app, very soon.
Is it possible somehow with your 4d-plugin-common-crypto or any other way?

4D v16
Mac OS X 10.14 Mojave

Thanks in advance

George Flórea
CIPOsoft Ltd.
Hungary

**Comment by miyako** [comment]
sha-3 support seems to have been introduced in openssl 1.1.1
https://www.openssl.org/docs/man1.1.1/man3/EVP_shake256.html

the plugin uses 1.1.0g from 2 Nov 2017

**Comment by miyako** [comment]
vcpkg is still at 1.0.2p 

https://github.com/Microsoft/vcpkg/issues/4267

**Comment by floreagyorgy** [comment]
Dear Miyako,
I'm really grateful for the implementation of SHA3. Thanks a lot.
George Flórea
CIPOsoft Ltd.
Hungary
